#!/bin/python3
import json
with open('io_def.json', 'r') as f:
    dat = json.load(f)
with open('io_def.xdc', 'w') as f:
    f.write('## This file is generated by json2xdc.py\n')
    f.write('## Do not modify this file manually\n')
    f.write('## Use json2xdc.py to regenerate this file\n')
    f.write('##\n')
    f.write('## Created by: \n')
    for i in dat:
        r = dat[i]
        if r.find('\'') != -1:
            continue
        if r.find('[') != -1:
            r = '{{{0}}}'.format(r)
        print('set_property -dict {{PACKAGE_PIN {0} IOSTANDARD LVCMOS33}} [get_ports {1}]'.format(i, r))
        f.write('set_property -dict {{PACKAGE_PIN {0} IOSTANDARD LVCMOS33}} [get_ports {1}]\n'.format(i, r))
